naam = input("Hallo, wat is je naam? ")
leeftijd = int(input(f"Goededag {naam}, hoe oud ben je? "))
faceten = input(f"En als {leeftijd} jarige, wat eet je het liefste? ")
facdrinken = input(f"En wat drink je het liefste bij {faceten}? ")
print()
print(f"De {leeftijd} jarige {naam} drinkt het liefste {facdrinken} bij {faceten} ")